### ISSUE TITLE
Warning: local variable 'y_min_rounded' referenced before assignment

### ISSUE THREAD

**Issue by Andreas-Piter** [luhipi/insar-explorer#42]
```
 Traceback (most recent call last):
              File "C:/Users/piter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\insar_explorer-dev\src\gui_controller.py", line 31, in 
              point=point, layer=None, ref=self.ui.pb_set_reference.isChecked()))
              File "C:/Users/piter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\insar_explorer-dev\src\map_click_handler.py", line 204, in choosePointClicked
              self.plot_ts.plotTs(dates=dates, ts_values=self.ts_values, ref_values=self.ref_values)
              File "C:/Users/piter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\insar_explorer-dev\src\plot_timeseries.py", line 66, in plotTs
              self.decoratePlot()
              File "C:/Users/piter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\insar_explorer-dev\src\plot_timeseries.py", line 108, in decoratePlot
              self.setYlims(ax=ax)
              File "C:/Users/piter/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\insar_explorer-dev\src\plot_timeseries.py", line 215, in setYlims
              y_min_rounded = np.min([y_min_rounded, -5])
             UnboundLocalError: local variable 'y_min_rounded' referenced before assignment
```

**Comment by mahmud1** [comment]
Thanks @Andreas-Piter for reporting the bug. It has already been fixed and will be included in v0.6.6.
